export default [
  ['organisasjonsnummer', 'orgNumber'],
  ['kode', 'code'],
  ['navn', 'name'],
  ['organisasjonsform', 'organizationForm'],
  ['beskrivelse', 'description'],
  ['registreringsdatoEnhetsregisteret', 'regDateOfEntities'],
  ['registrertIMvaregisteret', 'isRegistereInMvaRegister'],
  ['naeringskode1', 'industryCode'],
  ['antallAnsatte', 'employees'],
  ['forretningsadresse', 'businessAddress'],
  ['land', 'country'],
  ['landkode', 'countryCode'],
  ['postnummer', 'zip'],
  ['adresse', 'address'],
  ['poststed', 'postalLocation'],
  ['kommune', 'municipality'],
  ['kommunenummer', 'municipalityCode'],
  ['institusjonellSektorkode', 'institutionalSectorCode'],
  ['registrertIForetaksregisteret', 'registeredInTheRegisterOfBusinessEnterprises'],
  ['registrertIStiftelsesregisteret', 'registeredIinTheFoundationRegister'],
  ['registrertIFrivillighetsregisteret', 'registeredInTheVolunteerRegister'],
  ['konkurs', 'bankrupt'],
  ['underAvvikling', 'underSettlement'],
  ['underTvangsavviklingEllerTvangsopplosning', 'underCompulsoryLiquidationOrCompulsoryDissolution'],
  ['maalform', 'languageTargetForm']
] as Array<Array<string>>